ArFashion/ArFashion/Models/ErrorViewModel.cs
using System;

namespace ArFashion.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ArFashion/ArFashion/Models/HomeModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ArFashion.Models
{
    public class HomeModel
    {

    }
}

ArFashion/ArFashion/Models/Project.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ArFashion.Models
{
    public class Project
    {
        public int Id { get; set; }
        public string  Name { get; set; }
        public string Image { get; set; }
        public string Model { get; set; }

    }
}

ArFashion/ArFashion/Models/ViewModels/ProjectViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ArFashion.Models.ViewModels
{
    public class ProjectViewModel
    {
        public Project Project { get; set; }
    }
}

ArFashion/ArFashion/Controllers/HomeController.cs
using ArFashion.Data;
using ArFashion.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ArFashion.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _db;

        public HomeController(ILogger<HomeController> logger, ApplicationDbContext db)
        {
            _logger = logger;
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Project> objList = _db.Project;
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ArFashion/ArFashion/Controllers/ProjectController.cs
using ArFashion.Data;
using ArFashion.Models;
using ArFashion.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace ArFashion.Controllers
{
    public class ProjectController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IWebHostEnvironment _webHostEnvirnoment;


        public ProjectController(ApplicationDbContext db, IWebHostEnvironment webHostEnvironment)
        {
            _db = db;
            _webHostEnvirnoment = webHostEnvironment;
        }

        public IActionResult Index()
        {
            IEnumerable<Project> objList = _db.Project;
            return View(objList);
        }

        //Get-Create
        public IActionResult Create()
        {
            return View();
        }

        //Post-Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreatedProject(Project pvm)
        {
            //Collecting files from form
            var files = HttpContext.Request.Form.Files;
            string webRootPath = _webHostEnvirnoment.WebRootPath;

            string upload = webRootPath + WC.ImagePath;
            string fileName = Guid.NewGuid().ToString();

            string uploadModel = webRootPath + WC.ModelPath;
            string fileModelName = Guid.NewGuid().ToString();

            if(pvm.Name == null)
            {
                ModelState.AddModelError("Name", "Please insert project name");
                return View("Create");
            }

            if (files.Count() > 1)
            {
                string extension = Path.GetExtension(files[0].FileName);
                string extensionModel = Path.GetExtension(files[1].FileName);

                if (extension == ".jpg" || extension == ".jpeg" || extension == ".png")
                {
                    if (extensionModel == ".gltf")
                    {

                        using (var fileStream = new FileStream(Path.Combine(upload, fileName + extension), FileMode.Create))
                        {
                            files[0].CopyTo(fileStream);
                            files[1].CopyTo(fileStream);

                        }

                        using (var fileStream = new FileStream(Path.Combine(uploadModel, fileModelName + extensionModel), FileMode.Create))
                        {
                            files[1].CopyTo(fileStream);
                        }

                        pvm.Model = fileModelName + extensionModel;
                        pvm.Image = fileName + extension;

                        _db.Project.Add(pvm);
                        _db.SaveChanges();

                        RedirectToAction("Index");
                    }
                    else
                    {

                    ModelState.AddModelError("Model", "Please insert image with extension (jpg, jpeg, png) and model with extension (gltf)");
                    return View("Create");

                    }
                }
                else
                {
                    ModelState.AddModelError("Image", "Please insert image with extension (jpg, jpeg, png) and model with extension (gltf)");
                    return View("Create");
                }
            }
            else
            {

                ModelState.AddModelError("Model", "Please insert image and model");
                return View("Create");
            }

            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            Project pr = new Project();
            pr = _db.Project.Find(id);

            string webRootPath = _webHostEnvirnoment.WebRootPath;

            string filePath = webRootPath + WC.ImagePath + pr.Image;
            FileInfo file = new FileInfo(filePath);
            if (file.Exists)
            {
                file.Delete();
            }

            string fileModelPath = webRootPath + WC.ModelPath + pr.Model;
            FileInfo fileModel = new FileInfo(fileModelPath);
            if (fileModel.Exists)
            {
                fileModel.Delete();
            }

            _db.Project.Remove(pr);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        //Get-Create
        public IActionResult ViewCreated(int id)
        {
            Project project = new Project();
            project = _db.Project.Find(id);

            IEnumerable<Project> projects = _db.Project;
            ViewBag.projects = projects;

            return View(project);
        }

        [HttpGet]
        public IActionResult ViewPartial(int id)
        {
            Project project = new Project();
            project = _db.Project.Find(id);

            return PartialView("_ARPartialView", project);

        }

    }
}

ArFashion/ArFashion/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<body>
    <div class="text-center">
        <h1 class="display-4">Welcome</h1>
        <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    </div>
</body>

@*<style>
    .text-center {
        height: 500px;
        width:500px;
        background-image: url('/images/project/loader-cross-white-1x.png');
        background-repeat: repeat;
    }
</style>*@

ArFashion/ArFashion/Views/Project/Create.cshtml
@model ArFashion.Models.Project

<form method="post" enctype="multipart/form-data">
    <input asp-for="Id" hidden />
    <div class="row">
        <div class="col-8">

            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Name"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-4">
                    Upload Image
                </div>
                <div class="col-8">
                    <input type="file" name="files" id="uploadBox" multiple class="form-control" />
                    <span asp-validation-for="Image" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-4">
                    Upload Model
                </div>
                <div class="col-8">
                    <input type="file" name="files" id="uploadBox1" multiple class="form-control" />
                    <span asp-validation-for="Model" class="text-danger"></span>
                </div>
            </div>

            <a asp-controller="Project" asp-action="Index" class="btn btn-success w-25"> <i class="fas fa-sign-out-alt"></i> &nbsp;Back</a>
            <input type="submit" class="btn btn-primary w-25" asp-controller="Project" asp-action="CreatedProject" value="Submit" />

        </div>
    </div>
</form>

ArFashion/ArFashion/Views/Project/CreatedProject.cshtml
@{
    ViewData["Title"] = "CreatedProject";
}

<h1>CreatedProject</h1>

ArFashion/ArFashion/Views/Project/Index.cshtml
@model IEnumerable<ArFashion.Models.Project>


<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Project List</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-controller="Project" asp-action="Create" class="btn btn-primary">
                <i class="fas fa-plus"></i> &nbsp; Create New Project
            </a>
        </div>
    </div>

    <br />
    <br />

    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Project Name
                    </th>
                    <th>
                        Image
                    </th>
                    <th>
                        Model
                    </th>
                    <th>

                    </th>
                    <th>

                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                    <tr>
                        <td width="20%">@obj.Name</td>
                        <td><img src="@WC.ImagePath@obj.Image" class="offset-3" style="width:80px; height:50px;" /></td>
                        <td width="20%">@obj.Model</td>
                        <td width="20%">
                            <a asp-controller="Project" asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-danger w-100">
                                <i class="far fa-trash-alt"></i> &nbsp; Delete
                            </a>
                        </td>
                        <td width="20%">
                            <a asp-controller="Project" asp-action="ViewCreated" asp-route-id="@obj.Id" class="btn btn-primary w-100">
                                <i class="far fa-eye"></i> &nbsp; View
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>No projects exists.</p>
    }

</div>

        @section Scripts{
                <script>

                </script>
        }

ArFashion/ArFashion/Views/Project/ViewCreated.cshtml
@model ArFashion.Models.Project

<html>
<head>
    <meta name="viewport"
          content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="theme-color" content="#2D3142">
    <link rel="shortcut icon" type="~/image/png" href="favicon.png" />
    <link rel="stylesheet" href="~/common.css">
    <link rel="stylesheet" href="~/ar.css">
    <link rel="stylesheet" href="~/prism.css">
    <script src="~/view3d.pkgd.js"></script>
    <script src="~/prism.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js" type="text/javascript"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>

</head>

<body>

    <select class="btn btn-secondary dropdown-toggle" aria-label="Default select example" id="dropdown">
        @{

            foreach (var item in ViewBag.projects)
            {
                @if (@Model.Id == @item.Id)
                {
                    <option value="@item.Id" selected="selected" class="dropdown-item">
                        @Model.Name
                    </option>
                    continue;
                }
                <option value="@item.Id" class="dropdown-item">
                    @item.Name
                </option>
            }
        }
    </select>

    <br />
    <br />

    <div id="arPartial" style="height:700px;">
        <div id="loadingDiv">
            <img src="~/images/project/200w.webp" alt="Loading" class="imgLoader"/>
        </div>
    </div>
</body>

</html>
@section Scripts{

    <script>

        var $loading = $('#loadingDiv').hide();
        $(document)
            .ajaxStart(function () {
                $loading.show();
            })
            .ajaxStop(function () {
                $loading.hide();
            });

        $(document).ready(function () {
            $.ajax({
                url: "/Project/ViewPartial",
                type: 'GET',
                data: { id: $("#dropdown").val() },
                datatype: "json",
                success: function (response) {
                    $('#arPartial').html(response);
                },
                error: function (xhr) {
                    console.log($("#dropdown").val());
                    alert("Something went wrong, please try again");
                }
            });

            $('#dropdown').on('change', function () {
                $.ajax({
                    url: "/Project/ViewPartial",
                    type: 'GET',
                    data: { id: $("#dropdown").val() },
                    datatype: "json",
                    success: function (response) {
                        $('#arPartial').html(response);
                    },
                    error: function (xhr) {
                        console.log($("#dropdown").val());
                        alert("Something went wrong, please try again");
                    }
                });
            });
        });

    </script>
}

<style>
    #loadingDiv {
        position: relative;
        width: 100%;
        height: 100%;
        background-color: #050206;
    }
    .imgLoader {
        position: absolute;
        top: 250px;
        left: 450px;
    }
</style>

ArFashion/ArFashion/Views/Shared/_ARPartialView.cshtml
@model ArFashion.Models.Project
@{
    var imgPath = WC.ImagePath + Model.Image;
    var modelPath = WC.ModelPath + Model.Model;
}

<div id="view3d-wrapper">
    <div class="demo-wrapper">

        <div class="demo-desc-placeholder">
            <div class="demo-desc-wrapper">
                <h1 class="demo-title">FloorARSession</h1>
                <h2 class="demo-subtitle">
                    Fallback with <a href="https://developers.google.com/ar/develop/java/scene-viewer">Google SceneViewer</a> and <a href="https://developer.apple.com/augmented-reality/quick-look/">Apple AR Quick Look</a>
                </h2>
                <p class="demo-desc">Place you model on a detected floor</p>
            </div>
        </div>
    </div>
    <div class="view3d-canvas-wrapper">
        <canvas id="view3d-canvas"></canvas>
    </div>
</div>

<script>
        var {
            THREE,
            GLTFLoader,
            AutoDirectionalLight,
            ShadowPlane,
            Pose,
            OrbitControl,
            FloorARSession,
            SceneViewerSession,
            QuickLookSession,
        } = View3D;
        var view3d = new View3D('#view3d-canvas');
        var loader = new GLTFLoader();
        var textureLoader = new View3D.TextureLoader(view3d.renderer);
    textureLoader.loadHDRTexture("/images/project/urban_alley_01_2k.hdr", true).then(texture => {
        view3d.scene.setBackground(texture);
        view3d.scene.setEnvMap(texture);
    }).catch(e => console.error(e));

    ////////////////////////////OVDE UCITATI NOVU TEKSTURU////////////////////// //
    var loadedTexture = new THREE.TextureLoader().load('@imgPath');
    ////////////////////////////////////////////////////////////////////////////
        var light1 = new AutoDirectionalLight(0xffffff, 1.5, {
        direction: new THREE.Vector3(0.5, -2, -1)
    });

    view3d.scene.addEnv(light1);
    view3d.camera.setDefaultPose(new Pose(-45, 20, 100));

        var dressMaterial = new THREE.MeshStandardMaterial({
        map: loadedTexture,
    });

    view3d.controller.add(new OrbitControl());
    ////////////////////////////OVDE UCITATI NOVI MODEL//////////////////////
    /**/
        loader.load('@modelPath')
        /**/
        ////////////////////////////////////////////////////////////////////////////
        .then(model => {
            view3d.display(model, {
                size: 60
            });
            model.meshes[1].castShadow = false;
            view3d.animator.play(0);
            model.meshes[2].material = dressMaterial;
        });

        Prism.highlightAll();
</script>

ArFashion/ArFashion/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ArFashion</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/fontawesome/css/all.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ArFashion</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Project" asp-action="Index">My Projects</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ArFashion - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>